apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: is8u79rlq-python 
  janus-idp.io/tekton: is8u79rlq-python
  backstage.io/kubernetes-id: is8u79rlq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: is8u79rlq-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml