apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: is8u79rlq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: is8u79rlq-python 
  name: is8u79rlq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: is8u79rlq-python 
